console.log("Building build command...");

const cmd = new Deno.Command("lake", {
  args: ["lean", "Mathlib4Tactics.lean"],
});

console.log("Running build command...");

const { code, stdout, stderr } = await cmd.output();

const magicSeparator = "⊹---------------------⊹";

if (code !== 0) {
  console.error(
    `lake lean Mathlib4Tactics.lean exited with error code ${code}:`,
  );
  await Deno.stderr.write(stderr);
  Deno.exit(1);
}

const output = new TextDecoder().decode(stdout);

const [, tactics] = output.split(magicSeparator);

const readmeHeader = `# mathlib4-tactics

An autogenerated list of tactics from a modified \`#help tactic\`.

${tactics}
`;

await Deno.writeTextFile("README.md", readmeHeader);
